version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=test_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "3306:3306"

  front:
    build: ./front
    command: "yarn start"
    volumes:
      - ./front:/app_name
    ports:
      - 8000:8000
    tty: true

  back:
    build: ./back
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/myapp
    environment:
      - EDITOR="vim"
      - RAILS_ENV=development
      - MYAPP_DATABASE_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: