version: '3'

services:
  front:
    build: ./front
    command: yarn start
    volumes:
      - ./front:/app_name
    ports:
      - 8000:3000
    tty: true

  back:
    build: ./back
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s puma -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    environment:
      - EDITOR="vim"
      - RAILS_ENV=development
      - MYAPP_DATABASE_PASSWORD=password
    ports:
      - "3000:3000"
    # depends_on:
    #   - db

# volumes:
#   db-data: