FROM node:10.16.3-alpine

RUN mkdir /app_name 
ENV APP_ROOT /app_name 
WORKDIR $APP_ROOT

RUN npm install -g create-react-app
RUN npm install &&\
    yarn install --check-files && \
    curl --compressed -o- -L https://yarnpkg.com/install.sh | ash && \
    yarn upgrade && \

ADD . $APP_ROOT

CMD ["./node_modules/react-scripts/bin/react-scripts.js", "start"]